### ISSUE TITLE
Move Format Switcher to /js/formatSwitcher.js

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#10]
I copied it, but not implemented it.

**Comment by crutchcorn** [comment]
What is FormatSwitcher?

**Comment by crutchcorn** [comment]
Oh oh, is this the formatting for coloring? RGB vs Hex?

**Comment by crutchcorn** [comment]
Do the variables in the format chooser match up with the variables in formatSwitcher.js?

**Comment by danielhickman** [comment]
Yes, it needs to be moved after #9 is fixed.

**Comment by danielhickman** [comment]
Complete!
