### ISSUE TITLE
If ZeroClipBoard fails, Use Modal

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#13]
Until HTML5's clipbaord API is standard, flash may fail or not exist and Zero should be replaced with a modal telling them just that.

**Comment by crutchcorn** [comment]
Define Modal

**Comment by danielhickman** [comment]
"Use a modal for dialog boxes, confirmation messages, or other content that
can be called up."

**Comment by crutchcorn** [comment]
? I do no know what a modal IS.

**Comment by danielhickman** [comment]
materializecss.com/modals.html
