### ISSUE TITLE
Should We Use Google Adsense?

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#15]
- [x] Add GitHub Link
- [x] Google Analytics
- [ ] Google Adsense

**Comment by crutchcorn** [comment]
STOP FILLING MY INBOX. ROFL

**Comment by danielhickman** [comment]
It's left to Google Adsense. Should we or should we not? Maybe a card here and there with an ad. I am not sure if that would ruin any tool we put it on.

**Comment by danielhickman** [comment]
postponed until we have more features
