### ISSUE TITLE
??

### ISSUE THREAD

**Issue by AMQTech** [danielhickman/materialcolorize#2]
What is this and why am I subscribed to it!?

**Comment by crutchcorn** [comment]
Daniel.

**Comment by AMQTech** [comment]
Dude stop spamming my email lol


Andrew Quebe
Software Developer
(562) 267-9659

**Comment by AMQTech** [comment]
oooo! Commenting from my work email is awesome!

**Comment by crutchcorn** [comment]
I kinda want to... Lol.

I know... Though... Hmm... I could call that number.... >:D

**Comment by AMQTech** [comment]
It's just Google Voice...

**Comment by crutchcorn** [comment]
Darn

**Comment by danielhickman** [comment]
I'll explain this later in the group chat.

**Comment by AMQTech** [comment]
OK

Andrew Quebe
Software Developer
(562) 267-9659
