### ISSUE TITLE
Copy To Clipboard Quirks

### ISSUE THREAD

**Issue by crutchcorn** [danielhickman/materialcolorize#8]
- [x] You must click on the clipboard icon directly - if you don't it will not copy 
- [x] When you click in the right area, it scrolls you up all the way
- [ ] Clicking in the right area is clicking on an SWF - therefore the button does not have material animation. The fix should be using the JS output of zero to trigger the animation

**Comment by crutchcorn** [comment]
@danielhickman We might be able to fix the scrolling up issue with something such as 
<script>
$('#idname').click(function(e) {
     return false; 
     e.preventDefault(); 
});
<script>
<a href="#" id="idname">Stop me from scrolling</a>
But I'm not sure.. I tried just adding id to the <i> and it didn't work.. I suspect this is due to SWF behavior

**Comment by danielhickman** [comment]
script tags don't work in GitHub

```javascript
<script>
$('#idname').click(function(e) {
     return false; 
     e.preventDefault(); 
});
<script>
```
```html
<a href="#" id="idname">Stop me from scrolling</a>
```
But I'm not sure.. I tried just adding id to the <i> and it didn't work.. I suspect this is due to SWF behavior

**Comment by crutchcorn** [comment]
Dude, you and your italics today

**Comment by danielhickman** [comment]
LOL I copied you `<i>` and GitHub made it italic. :P I fixed it using instead of using href"#" use href"#!" (as long as you don't have anything with that id).

**Comment by crutchcorn** [comment]
Still though. :tongue:

**Comment by crutchcorn** [comment]
Wait I stupid

**Comment by danielhickman** [comment]
If you can move the clipbutton to <a> the onclick would not have to be the icon

**Comment by danielhickman** [comment]
https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/instructions.md#user-interaction-required

That means it is a limitation with zero that the ripple with never work, I'll be removing it until we use zero to trigger the animation
It completely covers the element with clip_button resulting in the CSS animation never being activated.

**Comment by danielhickman** [comment]
To address number 3:
Use this example to trigger the waves, make sure you add the waves-effect class along with the color being implemented.
```css
 .clip_button.zeroclipboard-is-hover { background-color: #eee; }
  .clip_button.zeroclipboard-is-active { background-color: #aaa; }
```

**Comment by crutchcorn** [comment]
NICE! :D Good work

**Comment by danielhickman** [comment]
Moved to #11.
