### ISSUE TITLE
Format Switcher Error

### ISSUE THREAD

**Issue by danielhickman** [danielhickman/materialcolorize#9]
`Uncaught ReferenceError: Invalid left-hand side in assignment` On `index.html: 24` or `formatSwitcher.js: 4`

**Comment by crutchcorn** [comment]
What does line 24 state?

**Comment by danielhickman** [comment]
```js
		document.getElementById("red-500-a").data-clipboard-text = "#f44336";
```
It's the first `data-clipboard-text` switcher (out of a few thousand)

**Comment by danielhickman** [comment]
That is currently erroring out the script, so format changing doesn't work at a whole, but it would without the `data-clipboard-text` switchers.

**Comment by danielhickman** [comment]
I believe that means it doesn't like the way I assigned the attribute. Although W3 Schools has a similar line without the error.
www.w3schools.com/js/tryit.asp?filename=tryjs_dom_image

**Comment by danielhickman** [comment]
This works, I'll be editing it, JS doesn't handle the dashes in `data-clipboard-text` so I'll rework the copy program to use `clipboard` instead
```javascript
document.getElementById("red-500-a").clipboard = "#ffffff";
```

**Comment by danielhickman** [comment]
Ended taking a different approach after investing time into reworking it. Which you can! It is on line 1002 of ZeroClipboard.js

I used a slightly different JS method. Wow that was a lot of work. I think that makes the color picker done until with get other things up.
